- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes
- name: Configure postfix mail type à 'Internet Site'
  ansible.builtin.debconf:
    name: postfix
    question: postfix/main_mailer_type
    value: 'Internet Site'
    vtype: string

- name: Configurer le nom d'hôte de Postfix
  ansible.builtin.debconf:
    name: postfix
    question: postfix/mailname
    value: "{{ domain_name }}"
    vtype: string

- name: Install postfix
  ansible.builtin.apt:
    name: postfix

- name: Redémarrer Postfix pour appliquer la configuration
  ansible.builtin.service:
    name: postfix
    state: restarted
    enabled: yes
