- name: Configurer Gmail comme relais SMTP
  ansible.builtin.lineinfile:
    path: /etc/postfix/main.cf
    regexp: '^relayhost ='
    line: "relayhost = {{ gmail_relay_host }}"
    state: present

- name: Activer l'authentification SMTP pour Gmail
  ansible.builtin.lineinfile:
    path: /etc/postfix/main.cf
    regexp: '^smtp_sasl_auth_enable ='
    line: 'smtp_sasl_auth_enable = yes'
    state: present

- name: Configurer les options de sécurité de l'authentification
  ansible.builtin.lineinfile:
    path: /etc/postfix/main.cf
    regexp: '^smtp_sasl_security_options ='
    line: 'smtp_sasl_security_options = noanonymous'
    state: present

- name: Créer le fichier d'authentification pour Gmail
  ansible.builtin.copy:
    dest: /etc/postfix/sasl_passwd
    content: |
      {{ gmail_relay_host }} {{ gmail_email }}:{{ gmail_app_password }}
    owner: rootst ça sest ça se
    group: root
    mode: '0600'

- name: Configurer le fichier d'authentification SMTP
  ansible.builtin.lineinfile:
    path: /etc/postfix/main.cf
    regexp: '^smtp_sasl_password_maps ='
    line: 'smtp_sasl_password_maps = hash:/etc/postfix/sasl_passwd'
    state: present

- name: Activer TLS pour sécuriser la communication avec Gmail
  ansible.builtin.lineinfile:
    path: /etc/postfix/main.cf
    regexp: '^smtp_tls_security_level ='
    line: 'smtp_tls_security_level = encrypt'
    state: present

- name: Spécifier le certificat CA pour les connexions TLS
  ansible.builtin.lineinfile:
    path: /etc/postfix/main.cf
    regexp: '^smtp_tls_CAfile ='
    line: 'smtp_tls_CAfile = /etc/ssl/certs/ca-certificates.crt'
    state: present

- name: Générer la base de données de mots de passe pour Postfix
  ansible.builtin.command:
    cmd: postmap /etc/postfix/sasl_passwd
  args:
    creates: /etc/postfix/sasl_passwd.db
